project:
  type: website
  output-dir: docs

website:
  title: "Lulu's Marketing Analytics Project"
  navbar:
    left:
      - href: index.qmd
        text: About
      - Resume.qmd
      - href: blog.qmd
        text: Projects

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



